spring:
  config:
    name: school
  datasource:
    url: jdbc:postgresql://localhost:5435/grantHoteldbLast
    username: postgres
    password: 1532
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql:
server:
  port: 8957
