name: Java Build, Syntax, and Style Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build, Syntax, and Style Check
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Настраиваем JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # Используем OpenJDK Temurin
          java-version: '21' # Укажите вашу версию Java

      # 3. Проверка синтаксиса (сборка проекта)
      - name: Compile project
        run: mvn compile # Для Gradle: ./gradlew classes

      # 4. Сборка проекта (без тестов)
      - name: Build project
        run: mvn clean package -DskipTests # Для Gradle: ./gradlew build -x test

      # 5. Проверка кода с SpotBugs
      - name: Run SpotBugs
        run: mvn spotbugs:check